
#theme: jekyll-theme-gitbook
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
plugins: 
  - jekyll-remote-theme
title: Micro curso de Julia
description: Micro curso de Julia para el Departamento de Matemática de Exactas - UBA. 