
#theme: jekyll-theme-gitbook
remote_theme: pages-themes/modernist@v0.2.0
#remote-theme: pages-themes/leap-day@v0.2.0
plugins: 
  - jekyll-remote-theme
title: Micro curso de Julia
description: Micro curso de Julia para el Departamento de Matemática de Exactas - UBA. 